"""Changed table name

Revision ID: 422b76657a13
Revises: 
Create Date: 2023-12-03 18:22:51.517773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422b76657a13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_event_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event_association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.eventId'], name='user_event_association_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_event_association_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name='user_event_association_pkey')
    )
    # ### end Alembic commands ###
